### ISSUE TITLE
smctl info returns user information even after `smctl logout`

### ISSUE THREAD

**Issue by freegroup** [Peripli/service-manager-cli#132]
If I login in with `smctl login....` the user context is set correct and I can get them with `smctl info`

```
>> smctl info
Service Manager URL: https://service-manager.cfapps.sap.hana.ondemand.com
User: andreas.herz@mycompany.com
 ```

But this information is still present after `smctl logout` , which seems to be wrong. 
```
>> smctl logout
You have successfully logged out.
>> smctl info  
Service Manager URL: https://service-manager.cfapps.sap.hana.ondemand.com
User: andreas.herz@mycompany.com
```

Is there any way to the get the context (user/subaccount domain) in which I'm logged in?

the help output of the `smctl` return, that `smctl info` should return the information of the logged user....but I'm logged out.

``` 
  help                Help about any command
  info                Prints information for logged user
  label               Label resource
 
```

**Comment by EpsilonTal** [comment]
Hello,

Thanks for the feedback.
A fix will be provided in the next released version.

Tal.

**Comment by pavelmaliy** [comment]
@freegroup 
> Is there any way to the get the context (user/subaccount domain) in which I'm logged in?

it's problematic, subdomain is passed as a parameter and relevant only for SAP, smctl is an open source and possible to  be integrated with other auth servers different then xsuaa, so Sub Account is an unknown terminology in cli point of view

**Comment by freegroup** [comment]
in this case it is maybe a good idea to add a option to return the passed parameter which I used during the login...or?

**Comment by EpsilonTal** [comment]
@freegroup, why won't you save locally the parameters you pass on the login, on your automatic script.
So you get a faster solution for your needs.

**Comment by freegroup** [comment]
*local storage* is a really bad idea. We want validate our setup and we do not trust any local tmp storage.

**Comment by pavelmaliy** [comment]
@freegroup I understand your need,
it seems like a feature request that need to be defined better.
From my point of view this feature is a bit strange, **info** is something that defined by the SM and not property bag of user that can store there any parameter that he passes in a login, I am not familiar with such behavior in any cli tool that I work with.

Anyway if this is something that absolutely must for you, you more than welcome to create a PR and we'll review it.
