### ISSUE TITLE
smctl delete-broker exits with code zero even if it fails

### ISSUE THREAD

**Issue by dotchev** [Peripli/service-manager-cli#33]
# Issue Template

### Step 1: Is this issue for here?

  * Since the Service Manager is comprised of multiple components (Service Manager,  Service Broker Proxies, Service Manager CLI, etc.) you should make sure that this is the right repository for your issue. Only issues related to the **Service Manager CLI** will be addressed here. All other issues should be created in the appropriate repositories in the [Peripli organization][1].
  * For general technical questions, send an email with your question on [service-manager-wg@googlegroups.com][2]

### Step 2: Describe the problem (very short text description):

`smctl delete-broker` exits with code zero even if it fails

#### Steps to reproduce:

  1. Try to delete a non-existing broker
  
#### Observed Results:
```
$ smctl delete-broker bb
Could not delete broker bb. Reason: URL: https://sm-host/v1/service_brokers/e6c67516-f7b9-44c1-a2a6-64d3decc333e, Status: 403; ErrorMessage: Forbidden; Description: Cause: Required scope "service_manager.broker.deregister" is missing from user token scopes [service_manager.broker.read service_manager.readBroker service_manager.readServiceCatalog service_manager.servicecatalog.read service_manager.broker.register service_manager.registerBroker]. Cause: Client id "service_manager_broker_admin" from user token is not trusted
Error: Broker with name: bb was not found

$ echo $?
0
```

```
$ smctl delete-broker none
Service Broker(s) not found

$ echo $?
0
```

#### Expected Results:

non-zero exit code
  
#### Relevant Code Snippet:

  
  [1]: https://github.com/Peripli
  [2]: service-manager-wg@googlegroups.com

**Comment by EpsilonTal** [comment]
Hello,

I suggest upgrading the version of the SMCTL as I could not reproduce the issue with the latest version.

`
service-manager-cli delete-broker bb             
Do you really want to delete broker with name [bb] (Y/n): y
Service Broker not found.
`
