### ISSUE TITLE
SMCTL cannot be installed

### ISSUE THREAD

**Issue by hummelo** [Peripli/service-manager-cli#52]
# Issue Template

### Step 1: Is this issue for here?

yes.

### Step 2: Describe the problem (very short text description):

 *I'm trying to install the CLI as described:
Approach 1: Manual installation
Download CLI
go get github.com/Peripli/service-manager-cli

Install CLI
go install github.com/Peripli/service-manager-cli/smctl

### Step 3: Describe the problem (steps):
 go get github.com/Peripli/service-manager-cli
 go install github.com/Peripli/service-manager-cli/smctl

#### Steps to reproduce:
  1.  go get github.com/Peripli/service-manager-cli
  2.  go install github.com/Peripli/service-manager-cli/smctl

#### Observed Results:
go install github.com/Peripli/service-manager-cli/smctl
can't load package: package github.com/Peripli/service-manager-cli/smctl: cannot find package "github.com/Peripli/service-manager-cli/smctl" in any of:
	/usr/local/go/src/github.com/Peripli/service-manager-cli/smctl (from $GOROOT)
	/Users/d036795/go/src/github.com/Peripli/service-manager-cli/smctl (from $GOPATH)
  
#### Expected Results:
  * SMCTL shall be installed successfully
  
#### Relevant Code Snippet:
NA

**Comment by dzahariev** [comment]
The documentation is updated.
