### ISSUE TITLE
smctl command not recognized in windows

### ISSUE THREAD

**Issue by ManoharGuptaKancharla** [Peripli/service-manager-cli#60]
# Issue Template

### Step 1: Is this issue for here?

smctl related issue.

### Step 2: Describe the problem (very short text description):

 I am trying to install service-manager-cli

#### Steps to reproduce:

  1. I was installing smctl for windows 64 bit.
  2. I have downloaded smactl_windows64.exe and added exe to the path.
  
#### Observed Results:

  * But the "smctl" command was not recognized. 
  
#### Expected Results:

  * "smctl" should have been recognized.
  

**After a long debugging, I understood that the smctl_windows64.exe has to be renamed to smctl.exe .
Please update your readme with this point.**
  
  
  [1]: https://github.com/Peripli
  [2]: service-manager-wg@googlegroups.com

**Comment by EpsilonTal** [comment]
Hello,

The readme file is updated with the installation guide already.
https://github.com/Peripli/service-manager-cli#rename-the-cli-binary
