### ISSUE TITLE
SM CLI refers to older version of Service Manager

### ISSUE THREAD

**Issue by risapisa** [Peripli/service-manager-cli#65]
The SM CLI will fail on installation due to referring to an older package name for the class LabelChanges.

The pull request from Service Manager which made these changes is here: https://github.com/Peripli/service-manager/pull/444

It seems like SM CLI should update the coding to reflect these changes, otherwise the installation of the tool will not work.

**Comment by risapisa** [comment]
In my case, I had to revert back to version 0.10.2 of the Service Manager in order to make the SM CLI tool work.

**Comment by EpsilonTal** [comment]
Is this issue still relevant? 
Re-open is it is.
