### ISSUE TITLE
OpenID unauthorized jwt malformed error 

### ISSUE THREAD

**Issue by shbert** [Peripli/service-manager-cli#77]
# Issue Template

### Step 1: Is this issue for here?

Most likely this issue is related to the cli, but could be also a combination of cli and service-manager api.

### Step 2: Describe the problem (very short text description):

After login the used token seem not to comply with JWS standards. Client returns: 
```
Error: request GET https://***/v1/platforms failed: StatusCode: 401 Body: {"error":"Unauthorized","description":"No authenticated user found: Cause: oidc: malformed jwt: square/go-jose: compact JWS format must have three parts"}
```
"***": is in reality the correct uri of the service-manager

### Step 3: Describe the problem (steps):

The entire test is based on a fresh and empty docker installation of the service-manager.

After integrating with a openid connect provider (community gitlab and turning on the openid feature) a login is executed successfully (client-id and user credential based), but as soon as I use any other command it returns the error message. The Bearer token is stored in local configuration file, but not in the required JWS format.

#### Executed commands
* Login
```
smctl_win64.exe login --auth-flow client-credentials --client-id foo --client-secret bar --config config-client.json --url https://*** 
```
(works and returns proper error messages as expected if something is wrong with credentials or settings in openid provider)

* Command
```
smctl_win64.exe list-platforms --config config-client.json
```
Turning on verbose does not reveal much more info besides: component=util/client.go:87

Same happens with a simple mocked openid provider service based on a node-oidc-provider.
  
#### Observed Results:

```
Error: request GET https://***/v1/platforms failed: StatusCode: 401 Body: {"error":"Unauthorized","description":"No authenticated user found: Cause: oidc: malformed jwt: square/go-jose: compact JWS format must have three parts"}
```  

### Used versions
* smctl_win64.exe (v1.10.6)
* service-manager (quay.io docker container "latest" and 0.13.4) 
  
  [1]: https://github.com/Peripli
  [2]: service-manager-wg@googlegroups.com

**Comment by shbert** [comment]
Additionally I just verified, if the token expired, the cli returns correctly with a "access token expired" error and asks for new log in

**Comment by EpsilonTal** [comment]
A new login is required.
Also, this issue is a bit old and we've updated our CLI with new features.
Try the latest version.
Reopen if the issue reproduces.
